name: bloc_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
    ^1.0.2

    ## PACAGES ##

  ## pakage to bloc
  flutter_bloc: ^8.1.3

  ## pakage to property delegte in main
  flutter_localizations:
    sdk: flutter

  ## pakage to save data
  shared_preferences: ^2.2.2

  ## package to connect internet
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5
  http: ^1.1.0
  bloc_concurrency: ^0.2.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/language/
